'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const domain = require('../domain/allianceWorkflow');
const providers = require('../domain/providerAdapters');

const input = { title: 'Regional delivery alliance', estimatedValueCents: 125000, currency: 'USD', partnerIds: ['p2', 'p1'], evidence: [{ uri: 'vault://evidence/1', sha256: 'a'.repeat(64) }] };
test('validates exact money, currency, evidence and normalized partners', () => { assert.deepEqual(domain.validateCase(input).partnerIds, ['p1', 'p2']); assert.throws(() => domain.validateCase({ ...input, estimatedValueCents: 1.2 }), /integer/); assert.throws(() => domain.validateCase({ ...input, evidence: [] }), /evidence/); });
test('enforces state, roles and independent bound approvals', () => { const owner = { id: 'owner', role: 'enterprise_partner' }; const admin = { id: 'admin', role: 'founding_orchestrator' }; const submitted = domain.applyCommand({ state: 'intake', version: 1, ownerId: 'owner' }, owner, 'submit'); assert.equal(submitted.state, 'conflict_review'); assert.throws(() => domain.applyCommand(submitted, owner, 'clear_conflict'), /role|approval/); const approved = { kind: 'conflict', decision: 'approved', requestedBy: 'owner', decidedBy: 'admin' }; assert.equal(domain.applyCommand(submitted, admin, 'clear_conflict', {}, approved).state, 'compliance_review'); assert.throws(() => domain.applyCommand(submitted, admin, 'clear_conflict', {}, { ...approved, decidedBy: 'owner' }), /independent/); });
test('tenant and participant scope fails closed', () => { const record = { tenantId: 't1', ownerId: 'owner', participantIds: ['participant'] }; assert.equal(domain.authorizeScope({ tenantId: 't1', id: 'participant', role: 'viewer' }, record), true); assert.throws(() => domain.authorizeScope({ tenantId: 't2', id: 'owner', role: 'admin' }, record), /cross-tenant/); assert.throws(() => domain.authorizeScope({ tenantId: 't1', id: 'stranger', role: 'viewer' }, record), /outside/); });
test('retry policy dead letters terminal failures and bounds backoff', () => { assert.equal(domain.nextDelivery(0, false).status, 'dead_letter'); assert.equal(domain.nextDelivery(0, true).status, 'retry'); assert.equal(domain.nextDelivery(4, true).status, 'dead_letter'); });
test('provider adapter sends typed idempotent calls and binds receipt hash', async () => { const old = { url: process.env.ALLIANCE_CRM_PROVIDER_URL, token: process.env.ALLIANCE_CRM_PROVIDER_TOKEN }; process.env.ALLIANCE_CRM_PROVIDER_URL = 'https://crm.example.test/v1'; process.env.ALLIANCE_CRM_PROVIDER_TOKEN = 'test-token'; let captured; const receipt = await providers.dispatch({ connector: 'crm', operation: 'case.upsert', idempotencyKey: 'provider-key-1', payload: { payloadHash: 'b'.repeat(64) }, fetchImpl: async (url, options) => { captured = { url, options }; return { ok: true, json: async () => ({ id: 'crm-1', payloadHash: 'b'.repeat(64) }) }; } }); assert.equal(receipt.id, 'crm-1'); assert.equal(captured.options.headers['idempotency-key'], 'provider-key-1'); if (old.url === undefined) delete process.env.ALLIANCE_CRM_PROVIDER_URL; else process.env.ALLIANCE_CRM_PROVIDER_URL = old.url; if (old.token === undefined) delete process.env.ALLIANCE_CRM_PROVIDER_TOKEN; else process.env.ALLIANCE_CRM_PROVIDER_TOKEN = old.token; });
test('provider adapter rejects generic, insecure, and mismatched calls', async () => { await assert.rejects(() => providers.dispatch({ connector: 'generic', operation: 'anything', idempotencyKey: 'provider-key-2', payload: {} }), /unsupported/); process.env.ALLIANCE_CLM_PROVIDER_URL = 'http://clm.example.test'; process.env.ALLIANCE_CLM_PROVIDER_TOKEN = 'x'; await assert.rejects(() => providers.dispatch({ connector: 'clm', operation: 'agreement.create', idempotencyKey: 'provider-key-3', payload: {} }), /HTTPS/); delete process.env.ALLIANCE_CLM_PROVIDER_URL; delete process.env.ALLIANCE_CLM_PROVIDER_TOKEN; });
test('migration owns persistent workflow, retry, tenant, one-use approvals, audit and receipt state', () => { const sql = fs.readFileSync(path.join(__dirname, '../db/migration_003_governed_alliance.sql'), 'utf8'); for (const term of ['alliance_memberships', 'alliance_cases', 'alliance_approvals', 'alliance_one_pending_approval_idx', 'consumed_at', 'alliance_case_events', 'alliance_delivery_jobs', 'alliance_provider_receipts', 'append-only']) assert.match(sql, new RegExp(term)); assert.doesNotMatch(sql, /DROP TABLE|TRUNCATE/i); });
test('server exposes the governed surface and retires generated/model routes', () => { const source = fs.readFileSync(path.join(__dirname, '../server.js'), 'utf8'); assert.match(source, /api\/v1\/alliance/); assert.match(source, /status\(410\)/); assert.doesNotMatch(source, /routes\/(ai|batch09GapAi|customViews|integrations)/); });
test('launcher and package scripts cannot destroy or silently mutate a workstation', () => { const source = fs.readFileSync(path.join(__dirname, '../../start.sh'), 'utf8'); const scripts = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8')).scripts; for (const mode of ['check)', 'migrate)', 'start)']) assert.match(source, new RegExp(mode.replace(')', '\\)'))); assert.match(source, /ALLOW_SCHEMA_MIGRATION/); assert.doesNotMatch(`${source}\n${JSON.stringify(scripts)}`, /kill\s+-9|DROP DATABASE|createdb|brew services|npm install|seed\.sql|alliance_pass|db:reset/); });
